export class System {
  public ID: number;
  public Name: string;
  public orgName: string;
  public FedContractorLoc: string;
  public FIPS_Impact_Level: string;
  public ATODate: Date;
  public ATOType: Date;
  public RenewalDate: Date;
  public ComplFISMA: string;
  public PII: string;
  public CloudYN: string;
  public CSP: string;
  public ServiceType: string;
  public FISMASystemIdentifier: string;
  public InactiveDate: Date;
  public Description: string;
  public SystemLevel: string;
  public SubSystem_Tag: string;
  public Reportable: string;
  public POC: string;
  public AO: string;
  public SO: string;
  public ISSM: string;
  public ISSO: string;
  public CO: string;
  public COR: string;
  public RelatedArtifacts: string;
}