export class Website {
  public website_id: string;
  public domain: string;
  public office: string;
  public sub_office: string;
  public contact_email: string;
  public site_owner_email: string;
  public production_status: string;
  public type_of_site: string;
  public digital_brand_category: string;
  public redirects_to: string;
  public cms_platform: string;
  public required_by_law_or_policy: string;
  public has_dap: string;
  public mobile_friendly: string;
  public has_search: string;
  public repository_url: string;
  public hosting_platform: string;
  public https: string;
  public customer_centricity: string;
  public mobile_performance: string;
  public google_analytics: string;
  public accessibility: string;
  public uswds: string;
  public required_links: string;
  public target_decommission_date: string;
  public sitemap_url: string;
  public obj_websites_Id: number;
}
